baseURL = "https://adamb35.github.io/TLLCER/"
languageCode = "en-us"
title = "TLLCER 2022/2023"
theme = "ananke"
publishDir = "Docs"

[params]
  text_color = ""
  author = ""
  favicon = ""
  site_logo = "sitelogo.jpg"
  description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3
